### ISSUE TITLE
"Invalid value for enum '\ElasticEmail\Model\EventType', must be one of: 'Submission', 'FailedAttempt', 'Bounce', 'Sent', 'Open', 'Click', 'Unsubscribe', 'Complaint'"

### ISSUE THREAD

**Issue by oleksandr-mykhailenko** [ElasticEmail/elasticemail-php#7]
Hello, for some messages I got interesting error.
Event type was not in the allowed list. And here is example of result that I got from the API

```
{
  "TransactionID": "e9173e6a-e237-4174-a06a-d8547d82630e",
  "MsgID": "Dw7ZNxeDhF8F5FDrJVYMaQ2",
  "FromEmail": "xxx@gmail.com",
  "To": "xxx@hotmail.com",
  "Subject": "Sit Down  . . .",
  "EventType": 30,
  "EventDate": "2023-11-10T13:30:10Z",
  "ChannelName": "HTTP API",
  "MessageCategory": "NotDelivered",
  "NextTryOn": null,
  "Message": "Delivery not attempted because Contact's status was 'Stale' at the time of sending.",
  "IPAddress": "",
  "PoolName": ""
},
{
  "TransactionID": "e9173e6a-e237-4174-a06a-d8547d82630e",
  "MsgID": "tUcpo8WogEx6yCgs5L9EHg2",
  "FromEmail": "xxx@gmail.com",
  "To": "xxxx@att.net",
  "Subject": "Sit Down  . . .",
  "EventType": 30,
  "EventDate": "2023-11-10T13:30:10Z",
  "ChannelName": "HTTP API",
  "MessageCategory": "NotDelivered",
  "NextTryOn": null,
  "Message": "Delivery not attempted because Contact's status was 'Stale' at the time of sending.",
  "IPAddress": "",
  "PoolName": ""
},
{
  "TransactionID": "e9173e6a-e237-4174-a06a-d8547d82630e",
  "MsgID": "AiAP7C3NWLdtKOeL8ePlGQ2",
  "FromEmail": "xxx@gmail.com",
  "To": "xxx@yahoo.com",
  "Subject": "Sit Down  . . .",
  "EventType": 30,
  "EventDate": "2023-11-10T13:30:10Z",
  "ChannelName": "HTTP API",
  "MessageCategory": "NotDelivered",
  "NextTryOn": null,
  "Message": "Delivery not attempted because Contact's status was 'Unsubscribed' at the time of sending.",
  "IPAddress": "",
  "PoolName": ""
},
```

I changed email from and email to, because it's users data. But other information right from the API CALL

I used api call `eventsByTransactionidGet`

```
string(164) "Invalid value for enum '\ElasticEmail\Model\EventType', must be one of: 'Submission', 'FailedAttempt', 'Bounce', 'Sent', 'Open', 'Click', 'Unsubscribe', 'Complaint'"
string(2284) "#0 /var/www/project/vendor/elasticemail/elasticemail-php/lib/ObjectSerializer.php(542): ElasticEmail\ObjectSerializer::deserialize(30, '\\ElasticEmail\\M...', NULL)
#1 /var/www/project/vendor/elasticemail/elasticemail-php/lib/ObjectSerializer.php(420): ElasticEmail\ObjectSerializer::deserialize(Object(stdClass), '\\ElasticEmail\\M...', NULL)
#2 /var/www/project/vendor/elasticemail/elasticemail-php/lib/Api/EventsApi.php(235): ElasticEmail\ObjectSerializer::deserialize(Array, '\\ElasticEmail\\M...', Array)
#3 /var/www/project/vendor/elasticemail/elasticemail-php/lib/Api/EventsApi.php(163): ElasticEmail\Api\EventsApi->eventsByTransactionidGetWithHttpInfo('e8173e03-de70-8...', NULL, NULL, NULL, NULL, NULL, 'application/jso...')
#4 /var/www/project/includes/Model/ElasticEmail/ElasticEmailLogService.php(106): ElasticEmail\Api\EventsApi->eventsByTransactionidGet('e8173e03-de70-8...')

```

**Comment by radzawee** [comment]
We have updated our library using the latest OpenAPI Generator, version 7.7.0.
